import 'facilities_model.dart';

List<FacilitiesModel> main_facilities_list = [
  FacilitiesModel("Amphitheater", "Some descriptions here blah blah",
      "assets/img/Amphitheater.png"),
  FacilitiesModel("Banda Kawayan, Sining Lahi Headquarters",
      "Some descriptions here blah blah", "assets/img/Unavailable.png"),
  FacilitiesModel("Building and Grounds Maintenance Office",
      "Some descriptions here blah blah", "assets/img/Unavailable.png"),
  FacilitiesModel(
      "Campus Development and Maintenance Building",
      "Some descriptions here blah blah",
      "assets/img/Unavailable.png"), // verify if same as building and grounds maintenance office
  FacilitiesModel("Centennial Monument", "Some descriptions here blah blah",
      "assets/img/Unavailable.png"),
  FacilitiesModel("Charlie del Rosario Bldg.",
      "Some descriptions here blah blah", "assets/img/Charlie-Bldg.png"),
  FacilitiesModel("East Gate", "Some descriptions here blah blah",
      "assets/img/Unavailable.png"),
  FacilitiesModel("Flagpole", "Some descriptions here blah blah",
      "assets/img/Unavailable.png",
      isAvailable: false), // disable
  FacilitiesModel("Grandstand", "Some descriptions here blah blah",
      "assets/img/Grandstand.png"),
  FacilitiesModel("Guard House", "Some descriptions here blah blah",
      "assets/img/Unavailable.png"),
  FacilitiesModel("Gymnasium", "Some descriptions here blah blah",
      "assets/img/Gymnasium.png"),
  FacilitiesModel("Interfaith Chapel", "Some descriptions here blah blah",
      "assets/img/Interfaith-Chapel.png"),
  FacilitiesModel("Laboratory High School", "Some descriptions here blah blah",
      "assets/img/Unavailable.png"),
  FacilitiesModel("Lagoon", "Some descriptions here blah blah",
      "assets/img/Unavailable.png"),
  FacilitiesModel("Main Building - Dome", "Some descriptions here blah blah",
      "assets/img/Unavailable.png"),
  FacilitiesModel("Main Building - East Wing",
      "Some descriptions here blah blah", "assets/img/Main-East.png"),
  FacilitiesModel("Main Building - North Wing",
      "Some descriptions here blah blah", "assets/img/Unavailable.png",
      isAvailable: false), // disable
  FacilitiesModel("Main Building - South Wing",
      "Some descriptions here blah blah", "assets/img/Southwing.png"),
  FacilitiesModel("Main Building - West Wing",
      "Some descriptions here blah blah", "assets/img/Main-West.png"),
  FacilitiesModel("Main Gate", "Some descriptions here blah blah",
      "assets/img/Unavailable.png"),
  FacilitiesModel("Nemesio E. Prudente Freedom Park",
      "Some descriptions here blah blah", "assets/img/Unavailable.png",
      isAvailable: false),
  FacilitiesModel("Ninoy Aquino Library", "Some descriptions here blah blah",
      "assets/img/Unavailable.png"),
  FacilitiesModel("Non-Food Stalls Building",
      "Some descriptions here blah blah", "assets/img/Unavailable.png"),
  FacilitiesModel("North Parking Area", "Some descriptions here blah blah",
      "assets/img/Unavailable.png"),
  FacilitiesModel("Nutrition and Food Science Building",
      "Some descriptions here blah blah", "assets/img/Nutrition.png"),
  FacilitiesModel("Open Court", "Some descriptions here blah blah",
      "assets/img/Unavailable.png",
      isAvailable: false), // disable
  FacilitiesModel(
      "Open University/Nontraditional Studies Program",
      "Some descriptions here blah blah",
      "assets/img/Unavailable.png"), // check if accurate yung facility
  FacilitiesModel("Oval Openfield", "Some descriptions here blah blah",
      "assets/img/Unavailable.png"),
  FacilitiesModel("Physical Education Building",
      "Some descriptions here blah blah", "assets/img/Unavailable.png"),
  FacilitiesModel("Printing Press Building", "Some descriptions here blah blah",
      "assets/img/Unavailable.png"),
  FacilitiesModel("Property and Supply Building",
      "Some descriptions here blah blah", "assets/img/Unavailable.png"),
  FacilitiesModel("PUP Linear Park", "Some descriptions here blah blah",
      "assets/img/Linear Park.png"),
  FacilitiesModel("PUP Obelisk", "Some descriptions here blah blah",
      "assets/img/Obelisk.png"),
  FacilitiesModel("PUP Sta. Mesa Ferry Station",
      "Some descriptions here blah blah", "assets/img/Unavailable.png"),
  FacilitiesModel("Pylon", "Some descriptions here blah blah",
      "assets/img/Unavailable.png"),
  FacilitiesModel("R.C. Overhead Water Tank",
      "Some descriptions here blah blah", "assets/img/Unavailable.png"),
  FacilitiesModel("Souvenir Shop", "Some descriptions here blah blah",
      "assets/img/Souvenir-Shop.png"), // gazebo
  FacilitiesModel("Student Canteen", "Some descriptions here blah blah",
      "assets/img/Student-Canteen.png"),
  FacilitiesModel("Swimming Pool", "Some descriptions here blah blah",
      "assets/img/Unavailable.png"),
  FacilitiesModel("Tahanan ng Alumni", "Some descriptions here blah blah",
      "assets/img/Alumni.png"),
  FacilitiesModel("Tennis Court", "Some descriptions here blah blah",
      "assets/img/Tennis-Court.png"),
  FacilitiesModel(
      "Visitors Information Center",
      "Some descriptions here blah blah",
      "assets/img/Visitors-Infor-Center.png"),
];
