import 'facilities_model.dart';

List<FacilitiesModel> main_facilities_list = [
  FacilitiesModel(
    "Amphitheater",
    "Located near at the lagoon and non-food stalls building",
    "assets/img/Amphitheater.png",
    isAvailable: true,
    facility_rooms: [],
  ),
  FacilitiesModel(
    "Banda Kawayan, Sining Lahi Headquarters",
    "Under construction",
    "assets/img/Unavailable.png",
    isAvailable: false,
    facility_rooms: [],
  ), // disable
  FacilitiesModel(
    "Campus Development and Maintenance Building",
    "Some descriptions here blah blah",
    "assets/img/Unavailable.png",
    isAvailable: true,
    facility_rooms: [],
  ), // same building as building and grounds maintenance office
  FacilitiesModel(
    "Charlie del Rosario Bldg.",
    "Some descriptions here blah blah",
    "assets/img/Charlie-Bldg.png",
    isAvailable: true,
    facility_rooms: [],
  ),
  FacilitiesModel(
    "Flagpole",
    "Under construction",
    "assets/img/Unavailable.png",
    isAvailable: false,
    facility_rooms: [],
  ), // disable
  FacilitiesModel(
    "Grandstand",
    "Some descriptions here blah blah",
    "assets/img/Grandstand.png",
    isAvailable: true,
    facility_rooms: [],
  ),
  FacilitiesModel(
    "Guard House",
    "Some descriptions here blah blah",
    "assets/img/Unavailable.png",
    isAvailable: true,
    facility_rooms: [],
  ),
  FacilitiesModel(
    "Interfaith Chapel",
    "Some descriptions here blah blah",
    "assets/img/Interfaith-Chapel.png",
    isAvailable: true,
    facility_rooms: [],
  ),
  FacilitiesModel(
    "Laboratory High School",
    "Some descriptions here blah blah",
    "assets/img/Unavailable.png",
    isAvailable: true,
    facility_rooms: [],
  ),
  FacilitiesModel(
    "Lagoon",
    "Some descriptions here blah blah",
    "assets/img/Unavailable.png",
    isAvailable: true,
    facility_rooms: [],
  ),
  FacilitiesModel(
    "Main Building - Dome",
    "Some descriptions here blah blah",
    "assets/img/Unavailable.png",
    isAvailable: true,
    facility_rooms: [],
  ),
  FacilitiesModel(
    "Main Building - East Wing",
    "Some descriptions here blah blah",
    "assets/img/Main-East.png",
    isAvailable: true,
    facility_rooms: [],
  ),
  FacilitiesModel(
    "Main Building - North Wing",
    "Under construction",
    "assets/img/Unavailable.png",
    isAvailable: false,
    facility_rooms: [],
  ), // disable
  FacilitiesModel(
    "Main Building - South Wing",
    "Some descriptions here blah blah",
    "assets/img/Southwing.png",
    isAvailable: true,
    facility_rooms: [
      'Accounting Office',
      'University Registrar',
      'Fund Mngt. Office',
      'Property Extension',
      'Budget Services',
      'Payroll Section',
      'S201-S520', // verify and change this
    ],
  ),
  FacilitiesModel(
    "Main Building - West Wing",
    "Some descriptions here blah blah",
    "assets/img/Main-West.png",
    isAvailable: true,
    facility_rooms: ['W101-W620'], // sample
  ),
  FacilitiesModel(
    "Main Gate",
    "Some descriptions here blah blah",
    "assets/img/Main-Gate.png",
    isAvailable: true,
    facility_rooms: [],
  ),
  FacilitiesModel(
    "Nemesio E. Prudente Freedom Park",
    "Under construction",
    "assets/img/Unavailable.png",
    isAvailable: false,
    facility_rooms: [],
  ), // disable
  FacilitiesModel(
    "Ninoy Aquino Library",
    "Some descriptions here blah blah",
    "assets/img/Unavailable.png",
    isAvailable: true,
    facility_rooms: [],
  ),
  FacilitiesModel(
    "Non-Food Stalls Building",
    "Some descriptions here blah blah",
    "assets/img/Unavailable.png",
    isAvailable: true,
    facility_rooms: [],
  ),
  FacilitiesModel(
    "North Parking Area",
    "Some descriptions here blah blah",
    "assets/img/Unavailable.png",
    isAvailable: true,
    facility_rooms: [],
  ),
  FacilitiesModel(
    "Nutrition and Food Science Building",
    "Some descriptions here blah blah",
    "assets/img/Nutrition.png",
    isAvailable: true,
    facility_rooms: [],
  ),
  FacilitiesModel(
    "Open Court",
    "Under construction",
    "assets/img/Unavailable.png",
    isAvailable: false,
    facility_rooms: [],
  ), // disable
  FacilitiesModel(
    "Oval Openfield",
    "Track and Field Oval",
    "assets/img/Unavailable.png",
    isAvailable: true,
    facility_rooms: [],
  ),
  FacilitiesModel(
    "Physical Education Building",
    "Some descriptions here blah blah",
    "assets/img/Unavailable.png",
    isAvailable: true,
    facility_rooms: [],
  ),
  FacilitiesModel(
    "Printing Press Building",
    "Some descriptions here blah blah",
    "assets/img/Unavailable.png",
    isAvailable: true,
    facility_rooms: [],
  ),
  FacilitiesModel(
    "Property and Supply Building",
    "Some descriptions here blah blah",
    "assets/img/Unavailable.png",
    isAvailable: true,
    facility_rooms: [],
  ),
  FacilitiesModel(
    "PUP Gymnasium",
    "Some descriptions here blah blah",
    "assets/img/Gymnasium.png",
    isAvailable: true,
    facility_rooms: [],
  ),
  FacilitiesModel(
    "PUP Linear Park",
    "Some descriptions here blah blah",
    "assets/img/Linear Park.png",
    isAvailable: true,
    facility_rooms: [],
  ),
  FacilitiesModel(
    "PUP Obelisk",
    "Mabini Monument is located here",
    "assets/img/Obelisk.png",
    isAvailable: true,
    facility_rooms: [],
  ),
  FacilitiesModel(
    "PUP Sta. Mesa Ferry Station",
    "Some descriptions here blah blah",
    "assets/img/Unavailable.png",
    isAvailable: true,
    facility_rooms: [],
  ),
  FacilitiesModel(
    "Pylon",
    "Some descriptions here blah blah",
    "assets/img/Pylon.png",
    isAvailable: true,
    facility_rooms: [],
  ),
  FacilitiesModel(
    "R.C. Overhead Water Tank",
    "Some descriptions here blah blah",
    "assets/img/Unavailable.png",
    isAvailable: true,
    facility_rooms: [],
  ),
  FacilitiesModel(
    "Souvenir Shop",
    "Some descriptions here blah blah",
    "assets/img/Souvenir-Shop.png",
    isAvailable: true,
    facility_rooms: [],
  ), // gazebo
  FacilitiesModel(
    "Student Canteen",
    "Some descriptions here blah blah",
    "assets/img/Student-Canteen.png",
    isAvailable: true,
    facility_rooms: [],
  ),
  FacilitiesModel(
    "Swimming Pool",
    "Some descriptions here blah blah",
    "assets/img/Pool.png",
    isAvailable: true,
    facility_rooms: [],
  ),
  FacilitiesModel(
    "Tahanan ng Alumni",
    "Some descriptions here blah blah",
    "assets/img/Unavailable.png",
    isAvailable: true,
    facility_rooms: [],
  ),
  FacilitiesModel(
    "Tahanan ng Atleta",
    "Some descriptions here blah blah",
    "assets/img/Atleta.png",
    isAvailable: true,
    facility_rooms: [],
  ),
  FacilitiesModel(
    "Tennis Court",
    "Some descriptions here blah blah",
    "assets/img/Tennis-Court.png",
    isAvailable: true,
    facility_rooms: [],
  ),
  FacilitiesModel(
    "Visitors Information Center",
    "Some descriptions here blah blah",
    "assets/img/Visitors-Infor-Center.png",
    isAvailable: true,
    facility_rooms: [],
  ),
];